Repository Les-Jailes/API_Rest, pull requests merged in 2023-11, with the labels that each got.

#2 Feature/id 03/api rest crud operations
  .env
  .gitignore
  README.md
  controllers/ProductsController.js
  controllers/UsersController.js
  controllers/controllers.txt
  models/ProductModel.js
  models/UserModel.js
  models/exampleModel.js
  package-lock.json
  package.json
  routes/ProductsRoutes.js
  routes/UsersRoutes.js
  routes/routes.txt
  server.js
Labels: feature

#3 Database product model enhancement in express server
  models/ProductModel.js
Labels: enhancement

#5 Required fields addded
  src/models/UserModel.js
Labels: feature

#7 Test environment
  .env
  server.js
Labels: feature

#9 Task/US-36/backend integration stripe
  .env
  package-lock.json
  package.json
  server.js
  src/controllers/CheckoutPaymentController.js
  src/models/CheckoutPaymentModel.js
  src/routes/CheckoutPaymentRoutes.js
Labels: feuture

#10 Task-43/Model Payment Updated Api-Rest
  src/controllers/CheckoutPaymentController.js
  src/controllers/ProductsController.js
  src/models/CheckoutPaymentModel.js
  src/models/ProductModel.js
Labels: task

#22 Deployment
  src/models/UserModel.js
Labels: deployment

#23 Feature/us cu 8686hh8vv/id 50 contact us page
  .env
  package-lock.json
  package.json
  server.js
  src/controllers/EmailController.js
  src/lib/EmailTemplate.js
  src/routes/EmailRoutes.js
Labels: feature

#24 testing deployment
  .env
  package-lock.json
  package.json
  server.js
  src/controllers/EmailController.js
  src/lib/EmailTemplate.js
  src/routes/EmailRoutes.js
Labels: deployment

#25 Task/id 49/product search engine backend api rest
  src/controllers/ProductsController.js
  src/routes/ProductsRoutes.js
Labels: feature

#26 Deploy
  src/controllers/ProductsController.js
  src/routes/ProductsRoutes.js
Labels: deployment
